# Generated by Django 4.0.3 on 2022-03-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_cartype'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cartypes',
            field=models.ManyToManyField(to='main_app.cartype'),
        ),
    ]
